package challenge.domain.exceptions

class OrderAlreadyPaidException : Exception("The order has already been paid!") {
}